export const GET_USERS_REQUEST_START = 'GET_USERS_REQUEST_START';
export const GET_USERS_REQUEST_SUCCESS = 'GET_USERS_REQUEST_SUCCESS';

export const GET_USER_REQUEST_START = 'GET_USER_REQUEST_START';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';

export const ADD_USER_REQUEST_START = 'ADD_USER_REQUEST_START';
export const ADD_USER_REQUEST_SUCCESS = 'ADD_USER_REQUEST_SUCCESS';

export const EDIT_USER_REQUEST_START = 'EDIT_USER_REQUEST_START';
export const EDIT_USER_REQUEST_SUCCESS = 'EDIT_USER_REQUEST_SUCCESS';

export const DELETE_USER_REQUEST_START = 'DELETE_USER_REQUEST_START';
export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';

export const OPEN_ADD_USER_MODAL = 'OPEN_ADD_USER_MODAL';
export const CLOSE_ADD_USER_MODAL = 'CLOSE_ADD_USER_MODAL';

export const OPEN_EDIT_USER_MODAL = 'OPEN_EDIT_USER_MODAL';
export const CLOSE_EDIT_USER_MODAL = 'CLOSE_EDIT_USER_MODAL';
